### ISSUE TITLE
Structure load always returns true

### ISSUE THREAD

**Issue by HielkePlugins** [Shynixn/StructureBlockLib#22]
When loading structures, I noticed something strange: the load method in PersistenceStructureService always returns true, even if target structure file doesn't exist. 

My code:

```java
PersistenceStructureService service = StructureBlockApi.INSTANCE.getStructurePersistenceService();
final StructureSaveConfiguration saveConfiguration = service.createSaveConfiguration("my_plugin", structurename,"world");

if (service.load(saveConfiguration, location)) {
    sendMessage(sender, "Loaded structure " + name);
} else {
    fail("Could not load structure " + name);
}

**Comment by Shynixn** [comment]
The server implementation of Minecraft stores structures on the main thread, even IO processes. So the structure should be placed or saved once the function finishes. Maybe I'll add a async implementation which completes when a structure has been saved or place?

I would recommend (for now) to store the save configurations of StructureBlockLib by yourself in order to perform checks in your code if the structure exists. 

Anyway, thanks for your feedback. I'll set #23 as future enhancement plan!

**Comment by HielkePlugins** [comment]
Yeah async would be really helpful! 
Right now saving/loading massive structures can freeze or even crash the server. 
I see this project as a potential "vanilla" replacement for schematics, but it should really handle bigger structures better!

I don't really understand how I can check if the structure exists with the save configurations. Do you mean checking if the .nbt file exists?

**Comment by Shynixn** [comment]
Yeah I think checking for the files is the most reliable way at the moment. If you like you can implement such a check (or even the async processing) in StructureBlockLib by yourself. Simply submit a pull request and I'll review it.
